name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "src/HttpRequestSpy.sln"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

      - name: Run tests
        run: dotnet test src/**/*Test*.csproj /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
