name: CI

on:
  push:
    branch: main
  pull_request:
    branch: main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SOLUTION: "src/HttpRequestSpy.sln"
      PACKAGE_PROJECT: "src/HttpRequestSpy/HttpRequestSpy.csproj"
      BUILD_CONFIG: "Release"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            8.0.x
            7.0.x
            6.0.x

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "6.0.x"
          includePrerelease: true

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration ${{ env.BUILD_CONFIG }} --no-restore

      - name: Run tests
        run: dotnet test src/**/*Test*.csproj --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack ${{ env.PACKAGE_PROJECT }} --configuration Release --output ./nupkg /p:Version=${{ env.GITVERSION_SEMVER }}
