name: CI

on:
  push:
    branch: main
  pull_request:
    branch: main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SOLUTION: "src/HttpRequestSpy.sln"
      BUILD_CONFIG: "Release"

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            8.0.x
            7.0.x
            6.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration ${{ env.BUILD_CONFIG }} --no-restore

      - name: Run tests
        run: dotnet test src/**/*Test*.csproj --no-restore --verbosity normal
