name: CI

on:
  push:
    branch: main
  pull_request:
    branch: main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SOLUTION: "src/HttpRequestSpy.sln"
      BUILD_CONFIG: "Release"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            8.0.x
            7.0.x
            6.0.x

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Generate BUILD_VERSION
        run: |
          $version = $(dotnet gitversion /showvariable SemVer)
          echo "BUILD_VERSION=$version"
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration ${{ env.BUILD_CONFIG }} --no-restore

      - name: Run tests
        run: dotnet test src/**/*Test*.csproj --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack --configuration Release --output ./nupkg /p:Version=${{ env.BUILD_VERSION }}
